version: "3.7"
services:
  php-fpm:
    build: ./laravel
    container_name: php-fpm
    restart: always
    expose:
      - 9000
    volumes:
      - ./laravel:/application
    depends_on:
      - postgres
      
  nginx:
    build: ./nginx
    container_name: nginx
    restart: always
    ports:
      - "8081:80"
    depends_on:
      - php-fpm

  postgres:
    image: postgres
    container_name: postgres
    environment:
      - POSTGRES_USER=user
      - POSTGRES_PASSWORD=123456
      - POSTGRES_DB=technews
    expose:
      - 5432
    ports: 
      - "5432:5432"
    volumes:
      - ./postgres:/var/lib/postgresql/data
